# -*- coding: utf-8 -*-
"""Flowers_CNN_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eEBSOyvsVq9LluwjmWqkYmIEvbo47m7F
"""

import kagglehub
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import numpy as np

path = kagglehub.dataset_download('alxmamaev/flowers-recognition')
print("Path to dataset files:", path)

datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.3,
    horizontal_flip=True,
    fill_mode='nearest',
    validation_split=0.2
)

train = datagen.flow_from_directory(
    '/kaggle/input/flowers-recognition/flowers',
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

validation = datagen.flow_from_directory(
    '/kaggle/input/flowers-recognition/flowers',
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

model = Sequential(
    [
        Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
        MaxPooling2D(2, 2),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D(2, 2),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D(2, 2),
        Flatten(),
        Dense(512, activation='relu'),
        Dropout(0.5),
        Dense(5, activation='softmax')
    ]
)

model.summary()

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(train, epochs=10, validation_data=validation)

loss, accuracy = model.evaluate(validation)
print(f'Test accuracy: {accuracy * 100:.2f}%')